### ISSUE TITLE
mmcv-full version 

### ISSUE THREAD

**Issue by Mark1Dong** [LARC-CMU-SMU/FoodSeg103-Benchmark-v1#6]
Firstly, Thanks for your reply about my questions, and I met the question: When I run this code with Pycharm connected to remote server, which need mmcv-full version less than 1.3.0. However，when it run in Mobaxterm/Xshell ,which I have installed the virtual environment, which need mmcv-full more than 1.3.7 and less than 1.4.0. And I do not know why it happened, I want to know whether or not you have met this questions.  
Secondly, I construct a moudle besed on fpn, but there are some questions :
Traceback (most recent call last):
  File "tools/train.py", line 165, in <module>
    main()
  File "tools/train.py", line 134, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/gpu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmseg/models/builder.py", line 46, in build_segmentor
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/gpu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/gpu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/gpu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "EncoderDecoder: 'FPNWA is not in the models registry'"
Traceback (most recent call last):
  File "/home/gpu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/gpu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 37, in __init__
    self.neck = builder.build_neck(neck)
  File "/home/gpu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmseg/models/builder.py", line 22, in build_neck
    return NECKS.build(cfg)
  File "/home/gpu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/gpu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/gpu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'FPNXX is not in the models

**Comment by XiongweiWu** [comment]
@Mark1Dong Hi, sorry for replying late. For your first problem, I guess this is because the official repo in mmcv has been updated, and thus there are some issues. You may install mmcv-full based on this command (the mmcv_version I use is 1.2.6):

`pip install mmcv-full=={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.6.0/index.html`

For your second question, I will check tmr, and hopefully I can solve it.
